### ISSUE TITLE
Deprecated Promise rejection warning

### ISSUE THREAD

**Issue by kennymark** [lukasolson/fitbit-node#25] opened 2018-01-29 14:20 UTC
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'req' of undefined
(node:39861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by katrin-krieger** [comment] 2018-02-08 19:10
I can confirm this bug. I tried to run the example and the error happens when the callback URI is called.

**Comment by jmdiego** [comment] 2018-02-09 02:25
Fixed in v2.1.0+001, since the only change is in the example file and not the module itself, the version has not actually changed.

**Closed as completed by jmdiego** 2018-02-09 02:25 UTC
